import enum

class SampleState(enum.Flag):
  READ = 0x0001
  NOT_READ = 0x0010
  ANY = 0xFFFF

class ViewState(enum.Flag):
  NEW = 0x0001
  NOT_NEW = 0x0010
  ANY = 0xFFFF

class InstanceState(enum.Flag):
  ALIVE = 0x0001
  NOT_ALIVE_DISPOSED = 0x0010
  NOT_ALIVE_NO_WRITERS = 0x0100
  NOT_ALIVE = 0x0006
  ANY = 0xFFFF

class ReturnCode(enum.IntEnum):
  OK = 0
  ERROR = 1
  UNSUPPORTED = 2
  BAD_PARAMETER = 3
  PRECONDITION_NOT_MET = 4
  OUT_OF_RESOURCES = 5
  NOT_ENABLED = 6
  IMMUTABLE_POLICY = 7
  INCONSISTENT_POLICY = 8
  ALREADY_DELETED = 9
  TIMEOUT = 10
  NO_DATA = 11
  ILLEGAL_OPERATION = 12

class StatusKind(enum.Flag):
  INCONSISTENT_TOPIC_STATUS = 1
  OFFERED_DEADLINE_MISSED_STATUS = 2
  REQUESTED_DEADLINE_MISSED_STATUS = 4
  OFFERED_INCOMPATIBLE_QOS_STATUS = 32
  REQUESTED_INCOMPATIBLE_QOS_STATUS = 64
  SAMPLE_LOST_STATUS = 128
  SAMPLE_REJECTED_STATUS = 256
  DATA_ON_READERS_STATUS = 512
  DATA_AVAILABLE_STATUS = 1024
  LIVELINESS_LOST_STATUS = 2048
  LIVELINESS_CHANGED_STATUS = 4096
  PUBLICATION_MATCHED_STATUS = 8192
  SUBSCRIPTION_MATCHED_STATUS = 16384
