module basic {
  enum ReadingKind {
    distance,
    speed,
    acceleration
  };

  struct Sample {
    long value;
    string where;
  };

  typedef sequence<Sample> seqSample;

  @topic
  struct Reading {
    ReadingKind kind;
    long value;
    string where;
    seqSample sampleSeq;
  };
};
